import {
  WiBarometer,
  WiCelsius,
  WiCloudy,
  WiDayCloudy,
  WiDayHail,
  WiDayHaze,
  WiDayRain,
  WiDayRainMix,
  WiDayShowers,
  WiDaySleet,
  WiDaySleetStorm,
  WiDaySnow,
  WiDaySnowThunderstorm,
  WiDaySnowWind,
  WiDaySprinkle,
  WiDayStormShowers,
  WiDaySunny,
  WiDayThunderstorm,
  WiFog,
  WiHorizon,
  WiHorizonAlt,
  WiHumidity,
  WiStrongWind,
  WiWindDeg,
} from 'react-icons/wi';

export const weatherCodeMapping = {
  0: WiDaySunny,
  1: WiDayHaze,
  2: WiDayCloudy,
  3: WiCloudy,
  45: WiFog,
  48: WiFog,
  51: WiDayRainMix,
  53: WiDayHail,
  55: WiDayRain,
  56: WiDayRainMix,
  57: WiDaySleetStorm,
  61: WiDayRainMix,
  63: WiDayShowers,
  65: WiDaySprinkle,
  66: WiDaySleet,
  67: WiDaySleet,
  71: WiDaySnowWind,
  73: WiDaySnowWind,
  75: WiDaySnowWind,
  77: WiDayHail,
  80: WiDayRainMix,
  81: WiDayStormShowers,
  82: WiDayThunderstorm,
  85: WiDaySnow,
  86: WiDaySnow,
  95: WiDayThunderstorm,
  96: WiDaySleetStorm,
  99: WiDaySnowThunderstorm,
};

export const weatherIconMappingDay = {
  0: '/weatherIcons/clear.png',
  1: '/weatherIcons/mainlyClear.png',
  2: '/weatherIcons/partlyCloudy.png',
  3: '/weatherIcons/overcast.png',
  45: '/weatherIcons/fog.png',
  48: '/weatherIcons/depositingRimeFog.png',
  51: '/weatherIcons/lightDrizzle.png',
  53: '/weatherIcons/modDrizzle.png',
  55: '/weatherIcons/denseDrizzle.png',
  56: '/weatherIcons/lowFreezingDrizzle.png',
  57: '/weatherIcons/highFreezingDrizzle.png',
  61: '/weatherIcons/lightRain.png',
  63: '/weatherIcons/modRain.png',
  65: '/weatherIcons/heavyRain.png',
  66: '/weatherIcons/lightFreezingRain.png',
  67: '/weatherIcons/heavyFreezingRain.png',
  71: '/weatherIcons/lightSnowfall.png',
  73: '/weatherIcons/modSnowfall.png',
  75: '/weatherIcons/heavySnowfall.png',
  77: '/weatherIcons/hail.png',
  80: '/weatherIcons/lightRainShowers.png',
  81: '/weatherIcons/modRainShowers.png',
  82: '/weatherIcons/violentRainShowers.png',
  85: '/weatherIcons/lightSnowShowers.png',
  86: '/weatherIcons/heavySnowShowers.png',
  95: '/weatherIcons/lightThunderstorm.png',
  96: '/weatherIcons/modThunderstorm.png',
  99: '/weatherIcons/thunderstormHail.png',
};

export const weatherIconMappingNight = {
  0: '/weatherIcons/clearMoon.png',
  1: '/weatherIcons/mainlyClearMoon.png',
  2: '/weatherIcons/partlyCloudyMoon.png',
  3: '/weatherIcons/overcast.png',
  45: '/weatherIcons/fogMoon.png',
  48: '/weatherIcons/depositingRimeFog.png',
  51: '/weatherIcons/lightDrizzle.png',
  53: '/weatherIcons/modDrizzle.png',
  55: '/weatherIcons/denseDrizzle.png',
  56: '/weatherIcons/lowFreezingDrizzle.png',
  57: '/weatherIcons/highFreezingDrizzle.png',
  61: '/weatherIcons/lightRain.png',
  63: '/weatherIcons/modRain.png',
  65: '/weatherIcons/heavyRain.png',
  66: '/weatherIcons/lightFreezingRain.png',
  67: '/weatherIcons/heavyFreezingRain.png',
  71: '/weatherIcons/lightSnowfall.png',
  73: '/weatherIcons/modSnowfall.png',
  75: '/weatherIcons/heavySnowfall.png',
  77: '/weatherIcons/hail.png',
  80: '/weatherIcons/lightRainShowersMoon.png',
  81: '/weatherIcons/modRainShowersMoon.png',
  82: '/weatherIcons/violentRainShowersMoon.png',
  85: '/weatherIcons/lightSnowShowersMoon.png',
  86: '/weatherIcons/heavySnowShowersMoon.png',
  95: '/weatherIcons/lightThunderstorm.png',
  96: '/weatherIcons/modThunderstorm.png',
  99: '/weatherIcons/thunderstormHail.png',
};
export const weatherLabelMapping = {
  0: 'clear sky',
  1: 'mainly clear',
  2: 'partly cloudy',
  3: 'overcast',
  45: 'fog',
  48: 'depositing rime fog',
  51: 'light drizzle',
  53: 'mod. drizzle',
  55: 'dense drizzle',
  56: 'lo freezing drizzle',
  57: 'hi freezing drizzle',
  61: 'light rain',
  63: 'mod. rain',
  65: 'heavy rain',
  66: 'light freezing rain',
  67: 'heavy freezing rain',
  71: 'light snowfall',
  73: 'mod. snowfall',
  75: 'heavy snowfall',
  77: 'hail',
  80: 'light rain showers',
  81: 'mod. rain showers',
  82: 'violent rain showers',
  85: 'light snow showers',
  86: 'heavy snow showers',
  95: 'light thunderstorm',
  96: 'mod. thunderstorm',
  99: 'thunderstorm & hail',
};
