export const weatherIconMappingDay = {
  0: '/weatherIcons/clear.png',
  1: '/weatherIcons/mainlyClear.png',
  2: '/weatherIcons/partlyCloudy.png',
  3: '/weatherIcons/overcast.png',
  45: '/weatherIcons/fog.png',
  48: '/weatherIcons/depositingRimeFog.png',
  51: '/weatherIcons/lightDrizzle.png',
  53: '/weatherIcons/modDrizzle.png',
  55: '/weatherIcons/denseDrizzle.png',
  56: '/weatherIcons/lowFreezingDrizzle.png',
  57: '/weatherIcons/highFreezingDrizzle.png',
  61: '/weatherIcons/lightRain.png',
  63: '/weatherIcons/modRain.png',
  65: '/weatherIcons/heavyRain.png',
  66: '/weatherIcons/lightFreezingRain.png',
  67: '/weatherIcons/heavyFreezingRain.png',
  71: '/weatherIcons/lightSnowfall.png',
  73: '/weatherIcons/modSnowfall.png',
  75: '/weatherIcons/heavySnowfall.png',
  77: '/weatherIcons/hail.png',
  80: '/weatherIcons/lightRainShowers.png',
  81: '/weatherIcons/modRainShowers.png',
  82: '/weatherIcons/violentRainShowers.png',
  85: '/weatherIcons/lightSnowShowers.png',
  86: '/weatherIcons/heavySnowShowers.png',
  95: '/weatherIcons/lightThunderstorm.png',
  96: '/weatherIcons/modThunderstorm.png',
  99: '/weatherIcons/thunderstormHail.png',
  100: '/weatherIcons/compass.png',
  101: '/weatherIcons/compass_white.png',
  102: '/weatherIcons/needle.png',
};

export const weatherIconMappingNight = {
  0: '/weatherIcons/clearMoon.png',
  1: '/weatherIcons/mainlyClearMoon.png',
  2: '/weatherIcons/partlyCloudyMoon.png',
  3: '/weatherIcons/overcast.png',
  45: '/weatherIcons/fogMoon.png',
  48: '/weatherIcons/depositingRimeFog.png',
  51: '/weatherIcons/lightDrizzle.png',
  53: '/weatherIcons/modDrizzle.png',
  55: '/weatherIcons/denseDrizzle.png',
  56: '/weatherIcons/lowFreezingDrizzle.png',
  57: '/weatherIcons/highFreezingDrizzle.png',
  61: '/weatherIcons/lightRain.png',
  63: '/weatherIcons/modRain.png',
  65: '/weatherIcons/heavyRain.png',
  66: '/weatherIcons/lightFreezingRain.png',
  67: '/weatherIcons/heavyFreezingRain.png',
  71: '/weatherIcons/lightSnowfall.png',
  73: '/weatherIcons/modSnowfall.png',
  75: '/weatherIcons/heavySnowfall.png',
  77: '/weatherIcons/hail.png',
  80: '/weatherIcons/lightRainShowersMoon.png',
  81: '/weatherIcons/modRainShowersMoon.png',
  82: '/weatherIcons/violentRainShowersMoon.png',
  85: '/weatherIcons/lightSnowShowersMoon.png',
  86: '/weatherIcons/heavySnowShowersMoon.png',
  95: '/weatherIcons/lightThunderstorm.png',
  96: '/weatherIcons/modThunderstorm.png',
  99: '/weatherIcons/thunderstormHail.png',
};
export const weatherLabelMapping = {
  0: 'clear sky',
  1: 'mainly clear',
  2: 'partly cloudy',
  3: 'overcast',
  45: 'fog',
  48: 'depositing rime fog',
  51: 'light drizzle',
  53: 'mod. drizzle',
  55: 'dense drizzle',
  56: 'lo freezing drizzle',
  57: 'hi freezing drizzle',
  61: 'light rain',
  63: 'mod. rain',
  65: 'heavy rain',
  66: 'light freezing rain',
  67: 'heavy freezing rain',
  71: 'light snowfall',
  73: 'mod. snowfall',
  75: 'heavy snowfall',
  77: 'hail',
  80: 'light rain showers',
  81: 'mod. rain showers',
  82: 'violent rain showers',
  85: 'light snow showers',
  86: 'heavy snow showers',
  95: 'light thunderstorm',
  96: 'mod. thunderstorm',
  99: 'thunderstorm & hail',
};

export const weatherBackgroundDay = {
  0: '/backgrounds/clear.jpg',
  1: '/backgrounds/clear.jpg',
  2: '/backgrounds/cloudy.jpg',
  3: '/backgrounds/cloudy.jpg',
  45: '/backgrounds/fog.jpg',
  48: '/backgrounds/fog.jpg',
  51: '/backgrounds/drizzle.jpg',
  53: '/backgrounds/drizzle.jpg',
  55: '/backgrounds/drizzle.jpg',
  56: '/backgrounds/freezing.jpg',
  57: '/backgrounds/freezing.jpg',
  61: '/backgrounds/rain.jpg',
  63: '/backgrounds/rain.jpg',
  65: '/backgrounds/rain.jpg',
  66: '/backgrounds/freezing.jpg',
  67: '/backgrounds/freezing.jpg',
  71: '/backgrounds/snow.jpg',
  73: '/backgrounds/snow.jpg',
  75: '/backgrounds/snow.jpg',
  77: '/backgrounds/hail.jpg',
  80: '/backgrounds/rainshowers.jpg',
  81: '/backgrounds/rainshowers.jpg',
  82: '/backgrounds/rainshowers.jpg',
  85: '/backgrounds/snowshowers.jpg',
  86: '/backgrounds/snowshowers.jpg',
  95: '/backgrounds/thunderstorm.jpg',
  96: '/backgrounds/thunderstorm.jpg',
  99: '/backgrounds/thunderstorm.jpg',
};

export const weatherBackgroundNight = {
  0: '/backgrounds/nightClear.jpg',
  1: '/backgrounds/nightClear.jpg',
  2: '/backgrounds/nightCloudy.jpg',
  3: '/backgrounds/nightCloudy.jpg',
  45: '/backgrounds/nightFog.jpg',
  48: '/backgrounds/nightFog.jpg',
  51: '/backgrounds/nightRain.jpg',
  53: '/backgrounds/nightRain.jpg',
  55: '/backgrounds/nightRain.jpg',
  56: '/backgrounds/freezing.jpg',
  57: '/backgrounds/freezing.jpg',
  61: '/backgrounds/nightRain.jpg',
  63: '/backgrounds/nightRain.jpg',
  65: '/backgrounds/nightRain.jpg',
  66: '/backgrounds/freezing.jpg',
  67: '/backgrounds/freezing.jpg',
  71: '/backgrounds/nightSnow.jpg',
  73: '/backgrounds/nightSnow.jpg',
  75: '/backgrounds/nightSnow.jpg',
  77: '/backgrounds/hail.jpg',
  80: '/backgrounds/nightRain.jpg',
  81: '/backgrounds/nightRain.jpg',
  82: '/backgrounds/nightRain.jpg',
  85: '/backgrounds/nightSnow.jpg',
  86: '/backgrounds/nightSnow.jpg',
  95: '/backgrounds/thunderstorm.jpg',
  96: '/backgrounds/thunderstorm.jpg',
  99: '/backgrounds/thunderstorm.jpg',
};
